# Generated by Django 5.2.8 on 2025-11-27 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_lesson_owner"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        auto_now=True,
                        help_text="Укажите дату платежа",
                        verbose_name="Дата платежа",
                    ),
                ),
                (
                    "amount",
                    models.IntegerField(
                        help_text="Укажите сумму платежа", verbose_name="Сумма платежа"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("CASH", "Наличные"), ("BANK_TRANSFER", "Перевод")],
                        help_text="Укажите метод платежа",
                        max_length=20,
                        verbose_name="метод платежа",
                    ),
                ),
                (
                    "session_id_course",
                    models.CharField(
                        blank=True,
                        help_text="Введите id курса",
                        max_length=300,
                        null=True,
                        verbose_name="id сессии курса",
                    ),
                ),
                (
                    "link_course",
                    models.URLField(
                        blank=True,
                        help_text="Укажите ссылку на оплату курса",
                        max_length=500,
                        null=True,
                        verbose_name="Ссылка на оплату курса",
                    ),
                ),
                (
                    "session_id_lesson",
                    models.CharField(
                        blank=True,
                        help_text="Введите id урока",
                        max_length=300,
                        null=True,
                        verbose_name="id сессии урока",
                    ),
                ),
                (
                    "link_lesson",
                    models.URLField(
                        blank=True,
                        help_text="Укажите ссылку на оплату урока",
                        max_length=500,
                        null=True,
                        verbose_name="Ссылка на оплату урока",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите оплаченный курс",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_course",
                        to="courses.course",
                        verbose_name="Оплаченный курс",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        blank=True,
                        help_text="Укажите оплаченный урок",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paid_lesson",
                        to="courses.lesson",
                        verbose_name="Оплаченный урок",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Укажите пользователя",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Платеж",
                "verbose_name_plural": "Платежи",
            },
        ),
    ]
