# Generated by Django 5.2.9 on 2025-12-16 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payments",
            old_name="link_course",
            new_name="link_pay",
        ),
        migrations.RenameField(
            model_name="payments",
            old_name="session_id_course",
            new_name="session_id",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="link_lesson",
        ),
        migrations.RemoveField(
            model_name="payments",
            name="session_id_lesson",
        ),
    ]
