# Generated by Django 5.2.9 on 2025-12-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="stripe_id",
            field=models.CharField(
                blank=True,
                help_text="id продукта в stripe",
                max_length=255,
                null=True,
                verbose_name="id продукта",
            ),
        ),
    ]
